# Generated by Django 2.2.5 on 2020-02-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalSpectrum', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('units', models.ManyToManyField(blank=True, related_name='system_pack', to='DigitalSpectrum.Unit')),
            ],
        ),
    ]
