# Generated by Django 2.2.5 on 2020-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalSpectrum', '0003_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
    ]
